Bundle class vendor prefixed
Algatux/influxdb-bundle pull request #64
Opened 2016-08-08 19:40 UTC by Algatux

related to #62 

- deprecated InfluxDbBundle
- added new AlgatuxInfluxDbBundle

2016-08-09 12:37 UTC, Soullivaneuh commented on UPGRADE-2.0.3.md
> +UPGRADE FROM 2.0.2 to 2.0.3
A deprecation **must** be on a minor, not a patch.

2016-08-09 12:38 UTC, Soullivaneuh commented on UPGRADE-2.0.3.md
> +UPGRADE FROM 2.0.2 to 2.0.3
http://semver.org/#spec-item-7

> It MUST be incremented if any public API functionality is marked as deprecated.

2016-08-09 12:38 UTC, Soullivaneuh commented on src/AlgatuxInfluxDbBundle.php
> + * Class AlgatuxInfluxDbBundle.
This class comment is not needed.

2016-08-09 12:38 UTC, Soullivaneuh commented on src/InfluxDbBundle.php
> + * Class InfluxDbBundle.
* Class comment not needed
* a `trigger_error` should be added outside the class.

2016-08-09 12:39 UTC, Algatux commented
So must we release a 3.x version?

2016-08-09 12:39 UTC, Soullivaneuh commented on tests/unit/AlgatuxInfluxDbBundleTest.php
> +class AlgatuxInfluxDbBundleTest extends AbstractContainerBuilderTestCase
`final` ?

2016-08-09 12:40 UTC, Algatux commented
No ok sorry 2.1.0

2016-08-09 12:44 UTC, Soullivaneuh commented
Also you should use titles and keep one `UPGRADE-2.x.md` file IMHO.

This works great, see example here: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/UPGRADE-3.x.md

2016-09-20 13:47 UTC, soullivaneuh requested changes
Changes on comments have to be made before merge.

2016-09-23 07:26 UTC, Algatux commented
Sorry I m actually on vacation and not able to do anything. Maybe next week

Il 20 set 2016 15:53, "Sullivan SENECHAL" <notifications@github.com> ha
scritto:

> *@Soullivaneuh* requested changes on this pull request.
>
> Changes on comments have to be made before merge.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Algatux/influxdb-bundle/pull/64#pullrequestreview-749564>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA2QILDt_toXfiEfCBPQOhwwSl_2YSQKks5qr-P2gaJpZM4JfZQ5>
> .
>

2016-10-14 19:09 UTC, Soullivaneuh commented
@Algatux It's always recommended to do the smooth way with deprecation.

After that, it's a matter of choice. The BC break is not a big change and can be put directly on a new major.

I'm not a big fan, but it's up to you. :wink:

2017-05-18 07:44 UTC, closed without merging