Fix broken field keys search request
Algatux/influxdb-bundle pull request #77
Opened 2018-01-29 15:31 UTC by Jerome1337

Fixes #76 

Use correct syntax for querying field keys

2018-01-29 16:17 UTC, Algatux commented
Hi @Jerome1337, thanks for the PR, we will review it asap.

2018-02-14 21:01 UTC, Soullivaneuh commented
@Algatux I'll checkout the fork and try it on my project ASAP.

2018-02-16 14:05 UTC, Algatux commented
@Soullivaneuh thx a lot!

2018-02-23 11:35 UTC, soullivaneuh requested changes
This indeed fix the issue with the latest versions of InfluxDB.

I left 1 request and Travis need to be fixed.

2018-02-23 11:35 UTC, Soullivaneuh commented on src/Form/Type/FieldKeyType.php
> +                        sprintf('SHOW FIELD KEYS FROM "%s"', $options['measurement']),
Please keep the previous sprintf multi-lines to have a clearer diff.

2018-02-26 09:33 UTC, Jerome1337 commented
@Algatux @Soullivaneuh I modified sprintf to multi-line. FYI the solution was found here : https://docs.influxdata.com/influxdb/v0.9/query_language/schema_exploration/#explore-field-keys-with-show-field-keys

2018-02-27 10:58 UTC, Soullivaneuh commented
@Jerome1337 Travis is still Failing.

2018-02-27 13:49 UTC, merged

2018-02-27 13:49 UTC, Soullivaneuh commented
Thank you @Jerome1337 !