Allow timeout/conectionTimeout for requests
Algatux/influxdb-bundle pull request #87
Opened 2018-11-26 14:14 UTC by Jerome1337

Fixes #86

2018-11-26 19:45 UTC, Algatux commented
Hi @Jerome1337! Thx for your work, I will checkand merge it Asap

2018-11-27 08:29 UTC, Algatux requested changes
I know that the values from configuration comes as they are but in future I want to enforce the strict typings on them, so please always specify the correct value type

2018-11-27 08:29 UTC, Algatux commented on README.MD
> +            timeout:              0
please specify .0 to be more strict on the type

2018-11-27 08:29 UTC, Algatux commented on README.MD
> +    timeout:              0
same here

2018-11-27 08:29 UTC, Algatux commented on src/DependencyInjection/Configuration.php
> +                            ->floatNode('timeout')->defaultValue(0)->end()
here too -> .0

2018-11-27 08:29 UTC, Algatux commented on src/Services/ConnectionFactory.php
> +        float $timeout = 0,
default must be .0

2018-11-27 08:29 UTC, Algatux commented on src/Services/ConnectionFactory.php
> +        float $timeout = 0,
here too :P

2018-11-27 09:19 UTC, Soullivaneuh commented on README.MD
> +            timeout:              0
Why? Does Guzzle accept float? :thinking:

2018-11-27 09:20 UTC, Soullivaneuh commented on README.MD
> +            timeout:              0
Forget my comment: http://docs.guzzlephp.org/en/stable/request-options.html#timeout

2018-11-27 09:46 UTC, soullivaneuh requested changes

2018-11-27 09:46 UTC, Soullivaneuh commented on README.MD
> +            # Setup timeout or connection timeout (seconds) for your requests
This should be also on the `info()` method of the configuration.

Please add this. The best thing to do for the documentation is to use `bin/console config:dump-reference` and copy/paste the result.

2018-11-27 10:08 UTC, Jerome1337 commented
@Algatux @Soullivaneuh I fixed your requested changes.

2018-11-27 10:14 UTC, merged

2018-11-27 10:14 UTC, Soullivaneuh commented
Thank you @Jerome1337

2018-11-27 10:16 UTC, Soullivaneuh commented
I'll made a release for this and the SSL feature @Algatux :+1: